### ISSUE TITLE
Odd Redraw Behavior

### ISSUE THREAD

**Issue by tylerrbrown** [Jay-Rad/Remotely#86]
Please see attached GIF created with CleanShot (thanks for that, BTW!).

http://bit.ly/38CzKDi

I have two windows side by side showing the same session. The one on the left is running on my computer in Firefox connected to the server over pretty good Internet (can send test speeds if necessary). The one on the right is running on a computer closer to the server (same subnet) but I am terminal severed into that session via RDP from my computer.

So the one on the left is straight to the remotely server, the one on the right is through RDP to home computer then to remotely server.

Note the tearing and artifacts.

I didn't change the quality level at all, but doing so doesn't seem to lower the "error" rate, just the overall quality.

I would expect the lag and weirdness to be on the session on the right since it has an extra "hop" through RDP.

Does this make sense?

Any way to overlay connection stats or any other ideas to diagnose. When I run a remote client session on the same subnet as the server it's great!

**Comment by tylerrbrown** [comment]
Just tested reversing it (server and remote target on same subnet viewing remote target on client over Internet) and it works a treat. So the issue is the lag when both the remote target and the client viewer are NOT local to the server.

**Comment by Jay-Rad** [comment]
I fixed an issue recently that was specific to Firefox.  Are you on an older version (before March)?  Does this happen when using Chrome or the new Edge (uses Chromium now)?

**Comment by tylerrbrown** [comment]
Yes, Chrome seems to just lag a little, no page tearing like Firefox does. I must be running an older version. 

I built it from source via docker pulling Remotely_Server_Linux-x64.zip, I'm guessing those assemblies aren't versioned, because the site is showing version 1.0.0.0 on the about page.  :(

Docker reports the container was built 3 weeks ago.

**Comment by tylerrbrown** [comment]
I dug it out of the container, it's 2020.02.13.1809, the fix come after that?

**Comment by Jay-Rad** [comment]
Yup, the fix came after.

**Comment by tylerrbrown** [comment]
I added versioning to my docker setup, and pushed version specific builds to my repo. Then I updated to 2020.02.14 without issue. Everything came up fine and dandy, all clients connected back in. 🥇 

I pushed 2020.03.07 and noted the database migration was necessary from your notes, so I extracted the SQL statements per the instructions for the tables Devices, RemotelyUsers and Organizations then I updated the Devices table adding the missing columns TotalMemory, TotalStorage, CpuUtilization, set the values for each row and new column to 0.0 and it imported successfully. 🥇 

I started 2020.03.07 up, and everything looked good, however none of the clients connected back in. I have physical access to one client, so I bounced the service on that machine, and still nothing.

I went back to 2020.03.07 and clients all connected back in.

In 2020.03.07 I turned logging up and see this when I restart the client service:

Parameters to hub method 'DeviceCameOnline' are incorrect.
System.IO.InvalidDataException: Deserializing object of the `Device` type for 'argument' failed.

...from:

`remotely.2020.03.07 | dbug: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[22]
remotely.2020.03.07 |       Parameters to hub method 'DeviceCameOnline' are incorrect.
remotely.2020.03.07 | System.IO.InvalidDataException: Error binding arguments. Make sure that the types of the provided values match the types of the hub method being invoked.
remotely.2020.03.07 |  ---> System.IO.InvalidDataException: Deserializing object of the `Device` type for 'argument' failed.
remotely.2020.03.07 |  ---> System.InvalidOperationException: code is invalid. code:199 format:ext 8
remotely.2020.03.07 |    at MessagePack.Decoders.InvalidArrayHeader.Read(Byte[] bytes, Int32 offset, Int32& readSize)
remotely.2020.03.07 |    at MessagePack.Formatters.DateTimeOffsetFormatter.Deserialize(Byte[] bytes, Int32 offset, IFormatterResolver formatterResolver, Int32& readSize)
remotely.2020.03.07 |    at MessagePack.Formatters.Remotely_Shared_Models_DeviceFormatter1.Deserialize(Byte[] , Int32 , IFormatterResolver , Int32& )
remotely.2020.03.07 |    at MessagePack.MessagePackSerializer.Deserialize[T](ArraySegment`1 bytes, IFormatterResolver resolver)
remotely.2020.03.07 |    at lambda_method(Closure , ArraySegment`1 , IFormatterResolver )
remotely.2020.03.07 |    at MessagePack.MessagePackSerializer.NonGeneric.Deserialize(Type type, ArraySegment`1 bytes, IFormatterResolver resolver)
remotely.2020.03.07 |    at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocol.DeserializeObject(Byte[] input, Int32& offset, Type type, String field, IFormatterResolver resolver)
remotely.2020.03.07 |    --- End of inner exception stack trace ---
remotely.2020.03.07 |    at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocol.DeserializeObject(Byte[] input, Int32& offset, Type type, String field, IFormatterResolver resolver)
remotely.2020.03.07 |    at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocol.BindArguments(Byte[] input, Int32& offset, IReadOnlyList`1 parameterTypes, IFormatterResolver resolver)
remotely.2020.03.07 |    --- End of inner exception stack trace ---
`

Any suggestions? I have quite a few remote clients connecting in, and I don't have physical access to most of them, so a smooth upgrade is paramount for me here.

Thank you for all your hard work on this project, do you have a donation page, Kickstarter or GoFundMe setup somewhere?

**Comment by tylerrbrown** [comment]
I built and tried 2020.03.08 as well, and see the same error in the log.

**Comment by tylerrbrown** [comment]
I spoke too soon, with server version 2020.02.14 the clients did show up, but I can't remote control them. (I see you changed to buttons in the grid). When I hit the remote control button it just opens up a new window with the "Connect to a client:" dialog, asking for name and session ID.

Rolled back to 2020.02.13.1809 and all clients connected back in, and I can remote again.

**Comment by Jay-Rad** [comment]
To be perfectly honest, I was waiting until I got closer to leaving beta before putting a priority on backwards compatibility, smooth upgrades, etc.  In these early stages, I've been making frequent and drastic changes as I try to figure out how I want things to be, so it hasn't been very feasible.

I'm still not even 100% sure if I want SQLite to be the default database, or Postgres.  :p  SQLite has made upgrades challenging because it doesn't support a lot of table alteration commands that others do.

However, I've been getting a lot of feedback lately, and it seems like it's time to really solidify things.

I think I'll need to make a separate "bridge" release for a no-touch agent upgrade.  I've been wanting to make the upgrade process more resilient, so this would be a good time to do it.

Just so you know what to expect, I'll have some updated agents to drop in the Downloads folder (without upgrading the whole server), and a new CurrentVersion.txt file.  Then restart the server and wait for all agents to update.  Once they've all updated, the latest server version can be installed.  The same database process will need to happen again.  Then everything should update like normal from then on.

I'll post back here when I have something ready.

**Comment by Jay-Rad** [comment]
Hey, I'd like to ask you some questions "off the record" to get some general feedback.  I rarely get to hear about how people are using Remotely, especially people using it at any sort of scale.

Would you mind exchanging some emails?  If not, please let me know at translucency@outlook.com. 

If you do mind, that's cool.  :)  I'll still report back here when I have something.

**Comment by Jay-Rad** [comment]
I'm closing this out since we followed up in email.
